package com.sprintmate.service;

import com.sprintmate.constant.GitHubConstants;
import com.sprintmate.model.User;
import com.sprintmate.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.security.oauth2.client.userinfo.DefaultOAuth2UserService;
import org.springframework.security.oauth2.client.userinfo.OAuth2UserRequest;
import org.springframework.security.oauth2.core.OAuth2AuthenticationException;
import org.springframework.security.oauth2.core.user.OAuth2User;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Custom OAuth2 user service that intercepts GitHub OAuth2 login success
 * and synchronizes user information with our local database.
 * 
 * Business Intent:
 * - When a user logs in via GitHub, we need to maintain a local User record
 * - New users are automatically registered on first login (zero-friction onboarding)
 * - Existing users have their profile info updated if GitHub data changed
 * 
 * This service bridges GitHub identity with our internal User entity.
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class CustomOAuth2UserService extends DefaultOAuth2UserService {

    private final UserRepository userRepository;

    /**
     * Intercepts OAuth2 login and synchronizes user data with local database.
     * Called automatically by Spring Security after successful GitHub authentication.
     *
     * Flow:
     * 1. Load user info from GitHub via parent class
     * 2. Extract relevant attributes (login, name)
     * 3. Check if user exists in our DB by GitHub URL
     * 4. Create new user or update existing user's info
     * 5. Return OAuth2User for Spring Security context
     *
     * @param userRequest OAuth2 request containing access token and client registration
     * @return OAuth2User with GitHub attributes for the authenticated session
     * @throws OAuth2AuthenticationException if authentication fails
     */
    @Override
    @Transactional
    public OAuth2User loadUser(OAuth2UserRequest userRequest) throws OAuth2AuthenticationException {
        // Delegate to parent to fetch user info from GitHub API
        OAuth2User oauth2User = super.loadUser(userRequest);

        // Synchronize GitHub user with our local database
        synchronizeUser(oauth2User);

        return oauth2User;
    }

    /**
     * Synchronizes GitHub user data with our local User entity.
     * Creates new user on first login, updates existing user if info changed.
     *
     * Business Rules:
     * - GitHub login is converted to full URL for consistent identification
     * - Name from GitHub is stored as 'name', can be split if surname needed later
     * - UUID is auto-generated by JPA for new users
     *
     * @param oauth2User The authenticated GitHub user
     */
    private void synchronizeUser(OAuth2User oauth2User) {
        // Extract GitHub attributes
        String login = oauth2User.getAttribute("login");
        String name = oauth2User.getAttribute("name");

        // Construct GitHub profile URL as unique identifier
        String githubUrl = GitHubConstants.GITHUB_BASE_URL + login;

        // Check if user already exists in our system
        var existingUser = userRepository.findByGithubUrl(githubUrl);

        if (existingUser.isPresent()) {
            // Existing user - update profile info if changed
            updateExistingUser(existingUser.get(), name);
        } else {
            // New user - create and persist
            createNewUser(githubUrl, name);
        }
    }

    /**
     * Updates an existing user's profile information if it has changed.
     * Only updates name for MVP - surname parsing can be added later if needed.
     *
     * @param user The existing user entity
     * @param name The current name from GitHub
     */
    private void updateExistingUser(User user, String name) {
        boolean updated = false;

        // Update name if different from stored value
        if (name != null && !name.equals(user.getName())) {
            user.setName(name);
            updated = true;
        }

        if (updated) {
            userRepository.save(user);
            log.info("Updated existing user: {}", user.getGithubUrl());
        } else {
            log.debug("No updates needed for user: {}", user.getGithubUrl());
        }
    }

    /**
     * Creates a new user entity from GitHub OAuth2 data.
     * UUID is auto-generated by JPA strategy defined in User entity.
     *
     * @param githubUrl The constructed GitHub profile URL
     * @param name The user's display name from GitHub
     */
    private void createNewUser(String githubUrl, String name) {
        var newUser = User.builder()
            .githubUrl(githubUrl)
            .name(name)
            .build();

        userRepository.save(newUser);
        log.info("Created new user: {}", githubUrl);
    }
}
